// Checks the TypeScript vault client against instruction bytes and account
// lists generated by the Rust program itself (solana/.../tests/encoding.rs).
import assert from "node:assert/strict";
import fs from "node:fs";
import { describe, it } from "node:test";
import { PublicKey, TransactionInstruction } from "@solana/web3.js";
import { TOKEN_PROGRAM, VaultProgram } from "../src/vaultProgram.js";

const fixture = JSON.parse(fs.readFileSync(new URL("./fixtures/vault-ix.json", import.meta.url), "utf8"));
const key = (n: number) => new PublicKey(Buffer.alloc(32, n));
const vp = new VaultProgram(new PublicKey(fixture.programId));
const [usdc, meme, admin, operator, guardian, jup] = [1, 2, 3, 4, 5, 6].map(key);

function check(name: string, ix: TransactionInstruction) {
  const want = fixture.instructions[name];
  assert.equal(ix.data.toString("hex"), want.data, `${name} data`);
  assert.deepEqual(
    ix.keys.map((k) => ({ pubkey: k.pubkey.toBase58(), isSigner: k.isSigner, isWritable: k.isWritable })),
    want.keys,
    `${name} accounts`,
  );
}

describe("vault program client matches the Rust program", () => {
  it("initialize", () =>
    check("initialize", vp.initialize({
      payer: admin, usdcMint: usdc, tokenProgram: TOKEN_PROGRAM, admin, operator, guardian, swapProgram: jup,
      usdcMaxOutflow: 150_000_000n, defaultSellBps: 2_000,
    })));

  it("registerAsset", () => check("registerAsset", vp.registerAsset(operator, meme, TOKEN_PROGRAM)));

  it("swap (clears the PDA's signer flag from the route)", () =>
    check("swap", vp.swap({
      operator, orderId: 42n, amountIn: 100_000_000n, minOut: 5_000_000n, mintIn: usdc, mintOut: meme,
      tokenProgramIn: TOKEN_PROGRAM, tokenProgramOut: TOKEN_PROGRAM,
      route: new TransactionInstruction({
        programId: jup,
        keys: [
          { pubkey: vp.vault, isSigner: true, isWritable: false },
          { pubkey: key(9), isSigner: false, isWritable: true },
        ],
        data: Buffer.from("deadbeef", "hex"),
      }),
    })));

  it("withdraw", () =>
    check("withdraw", vp.withdraw({ admin, mint: usdc, tokenProgram: TOKEN_PROGRAM, destination: key(7), amount: 1_000_000n })));

  it("setAssetCaps", () => check("setAssetCaps", vp.setAssetCaps(admin, meme, 5n, 300)));

  it("updateConfig", () =>
    check("updateConfig", vp.updateConfig(admin, { operator: key(8), defaultSellBps: 1_000, paused: false })));

  it("pause / admin handover", () => {
    check("pause", vp.pause(guardian));
    check("proposeAdmin", vp.proposeAdmin(admin, key(8)));
    check("acceptAdmin", vp.acceptAdmin(key(8)));
  });
});
