/**
 * Reference off-chain keeper for the battle_vault program.
 *
 * STATUS: this is what a real keeper looks like, written against the
 * program's instruction interface — but it has not been run, because the
 * program (see /program) has not been built or deployed anywhere. There is
 * no IDL file yet for it to load. The frontend's Battles/CommonCoins pages
 * simulate this same logic client-side in the browser for the demo; this
 * script is the production replacement for that simulation, not something
 * this repo currently runs.
 *
 * What it actually does, once the program is deployed and its IDL exists at
 * program/target/idl/battle_vault.json (generated by `anchor build`):
 *   1. Poll all Battle accounts on-chain.
 *   2. Filter to ones that have an opponent, aren't settled yet, and whose
 *      `ends_at` has passed.
 *   3. Look up the registered Pyth price feed for each side's mint.
 *   4. Call `settle_battle` — permissionless, so this keypair only ever
 *      pays the small tx fee, never anyone's stake.
 *
 * Anyone could run this (that's the point of settlement being
 * permissionless), but a single reliable runner is what makes battles
 * resolve promptly in practice.
 */
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import * as anchor from '@coral-xyz/anchor'
import { Connection, Keypair, PublicKey } from '@solana/web3.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const RPC_URL = process.env.RPC_URL ?? 'https://api.devnet.solana.com'
const PROGRAM_ID = process.env.PROGRAM_ID
const KEEPER_KEYPAIR_PATH = process.env.KEEPER_KEYPAIR_PATH ?? '~/.config/solana/id.json'
const POLL_INTERVAL_MS = Number(process.env.POLL_INTERVAL_MS ?? 15_000)

function loadKeypair(rawPath: string): Keypair {
  const expanded = rawPath.startsWith('~')
    ? path.join(process.env.HOME ?? '', rawPath.slice(1))
    : rawPath
  const secret = JSON.parse(readFileSync(expanded, 'utf8'))
  return Keypair.fromSecretKey(Uint8Array.from(secret))
}

function loadIdl(programId: string): anchor.Idl {
  const idlPath = path.join(__dirname, '../../program/target/idl/battle_vault.json')
  let idl: anchor.Idl
  try {
    idl = JSON.parse(readFileSync(idlPath, 'utf8'))
  } catch {
    throw new Error(
      `Could not read ${idlPath}. Run \`anchor build\` in /program first — this keeper ` +
        `has nothing to talk to until the program is built and its IDL exists.`,
    )
  }
  // Anchor 0.30's IDL format carries the program address inline; override it
  // with PROGRAM_ID so this can point at whichever deployment you're running.
  idl.address = programId
  return idl
}

function pda(programId: PublicKey, seeds: (Buffer | Uint8Array)[]): PublicKey {
  return PublicKey.findProgramAddressSync(seeds, programId)[0]
}

async function main() {
  if (!PROGRAM_ID) {
    throw new Error('Set PROGRAM_ID to the deployed battle_vault program address.')
  }

  const idl = loadIdl(PROGRAM_ID)
  const programId = new PublicKey(PROGRAM_ID)
  const connection = new Connection(RPC_URL, 'confirmed')
  const keeper = loadKeypair(KEEPER_KEYPAIR_PATH)
  const wallet = new anchor.Wallet(keeper)
  const provider = new anchor.AnchorProvider(connection, wallet, { commitment: 'confirmed' })
  const program = new anchor.Program(idl, provider)
  // IDL is loaded from disk at runtime, so TS can't statically know its
  // account names — `accounts` gives untyped-but-correct dynamic access.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const accounts = program.account as any

  console.log(`Keeper ${keeper.publicKey.toBase58()} watching program ${programId.toBase58()}`)
  console.log(`Polling every ${POLL_INTERVAL_MS}ms against ${RPC_URL}`)

  async function tick() {
    const now = Math.floor(Date.now() / 1000)
    let battles: anchor.ProgramAccount<Record<string, unknown>>[]
    try {
      battles = await accounts.battle.all()
    } catch (err) {
      console.error('Failed to fetch battle accounts:', err)
      return
    }

    const due = battles.filter((b) => {
      const acc = b.account as {
        opponent: PublicKey | null
        settled: boolean
        endsAt: anchor.BN
      }
      return acc.opponent && !acc.settled && Number(acc.endsAt) <= now
    })

    if (due.length === 0) {
      console.log(`[${new Date().toISOString()}] nothing due`)
      return
    }

    for (const { publicKey: battlePubkey, account } of due) {
      const b = account as {
        creator: PublicKey
        opponent: PublicKey
        mintA: PublicKey
        mintB: PublicKey
      }
      try {
        const feedA = pda(programId, [Buffer.from('feed'), b.mintA.toBuffer()])
        const feedB = pda(programId, [Buffer.from('feed'), b.mintB.toBuffer()])
        const feedConfigA = await accounts.feedConfig.fetch(feedA)
        const feedConfigB = await accounts.feedConfig.fetch(feedB)

        const vaultStateA = pda(programId, [
          Buffer.from('vault'),
          b.creator.toBuffer(),
          b.mintA.toBuffer(),
        ])
        const vaultStateB = pda(programId, [
          Buffer.from('vault'),
          b.opponent.toBuffer(),
          b.mintB.toBuffer(),
        ])
        const vaultTokenA = pda(programId, [
          Buffer.from('vault-token'),
          b.creator.toBuffer(),
          b.mintA.toBuffer(),
        ])
        const vaultTokenB = pda(programId, [
          Buffer.from('vault-token'),
          b.opponent.toBuffer(),
          b.mintB.toBuffer(),
        ])
        const escrowA = pda(programId, [
          Buffer.from('escrow'),
          b.creator.toBuffer(),
          Buffer.from('a'),
          battlePubkey.toBuffer(),
        ])
        const escrowB = pda(programId, [
          Buffer.from('escrow'),
          b.creator.toBuffer(),
          Buffer.from('b'),
          battlePubkey.toBuffer(),
        ])

        const sig = await program.methods
          .settleBattle()
          .accounts({
            payer: keeper.publicKey,
            battle: battlePubkey,
            vaultStateA,
            vaultTokenA,
            vaultStateB,
            vaultTokenB,
            escrowA,
            escrowB,
            pythPriceA: (feedConfigA as { pythPriceAccount: PublicKey }).pythPriceAccount,
            pythPriceB: (feedConfigB as { pythPriceAccount: PublicKey }).pythPriceAccount,
            tokenProgram: anchor.utils.token.TOKEN_PROGRAM_ID,
          })
          .rpc()

        console.log(`Settled battle ${battlePubkey.toBase58()} — tx ${sig}`)
      } catch (err) {
        console.error(`Failed to settle battle ${battlePubkey.toBase58()}:`, err)
      }
    }
  }

  await tick()
  setInterval(tick, POLL_INTERVAL_MS)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
